### ISSUE TITLE
Build problems (possible too new ocaml?)

### ISSUE THREAD

**Issue by alerque** [rlepigre/ocaml-earley#7] opened 2023-12-27 20:22 UTC
I'm trying to package this in an Arch Linux package as a dependency for something else I want to package and try (Patoline), but I'm having trouble building it. In a clean chroot I have:

```
ocaml-5.1.0
dune-3.11.1
ocaml-stdlib-shims-0.3.0
ocaml-findlib-1.9.6
```

...plus of course some standard build tooling and system libraries.

After extracting the 2.0.0 source archive, I'm trying to build with this outcome:

```console
$ dune build
File "pa_ocaml/dune", line 16, characters 0-342:
16 | (rule
17 |   (targets helper.ml helper.mli astextra.ml astextra.mli)
18 |   (action (progn
19 |     (copy ../static/helpers/%{ocaml_version}/helper.ml helper.ml)
20 |     (copy ../static/helpers/helper.mli helper.mli)
21 |     (copy ../static/helpers/%{ocaml_version}/astextra.ml astextra.ml)
22 |     (copy ../static/helpers/%{ocaml_version}/astextra.mli astextra.mli))))
Error: No rule found for static/helpers/5.1.0/astextra.ml
File "pa_ocaml/dune", line 24, characters 0-525:
24 | (rule
25 |   (targets compare.ml)
26 |   (action (with-stdout-to compare.ml (progn
....
34 |     ../static/tools/generic_eq.ml
35 |     ../static/tools/%{ocaml_version}/asttypes.mli
36 |     ../static/tools/%{ocaml_version}/parsetree.mli))
Error: No rule found for static/tools/5.1.0/asttypes.mli
File "pa_ocaml/dune", line 16, characters 0-342:
16 | (rule
17 |   (targets helper.ml helper.mli astextra.ml astextra.mli)
18 |   (action (progn
19 |     (copy ../static/helpers/%{ocaml_version}/helper.ml helper.ml)
20 |     (copy ../static/helpers/helper.mli helper.mli)
21 |     (copy ../static/helpers/%{ocaml_version}/astextra.ml astextra.ml)
22 |     (copy ../static/helpers/%{ocaml_version}/astextra.mli astextra.mli))))
Error: No rule found for static/helpers/5.1.0/astextra.mli
File "pa_ocaml/dune", line 16, characters 0-342:
16 | (rule
17 |   (targets helper.ml helper.mli astextra.ml astextra.mli)
18 |   (action (progn
19 |     (copy ../static/helpers/%{ocaml_version}/helper.ml helper.ml)
20 |     (copy ../static/helpers/helper.mli helper.mli)
21 |     (copy ../static/helpers/%{ocaml_version}/astextra.ml astextra.ml)
22 |     (copy ../static/helpers/%{ocaml_version}/astextra.mli astextra.mli))))
Error: No rule found for static/helpers/5.1.0/helper.ml
File "pa_ocaml/dune", line 24, characters 0-525:
24 | (rule
25 |   (targets compare.ml)
26 |   (action (with-stdout-to compare.ml (progn
....
34 |     ../static/tools/generic_eq.ml
35 |     ../static/tools/%{ocaml_version}/asttypes.mli
36 |     ../static/tools/%{ocaml_version}/parsetree.mli))
Error: No rule found for static/tools/5.1.0/parsetree.mli
File "boot/dune", line 8, characters 0-1196:
 8 | (rule
 9 |   (targets
10 |     astextra.ml
....
36 |     (copy ../static/boot/%{ocaml_version}/pa_ocaml_prelude.ml pa_ocaml_prelude.ml)
37 |     (copy ../static/boot/%{ocaml_version}/pa_parser.ml pa_parser.ml)
38 |     (copy ../static/boot/%{ocaml_version}/quote.ml quote.ml))))
Error: No rule found for static/boot/5.1.0/astextra.ml
File "boot/dune", line 8, characters 0-1196:
 8 | (rule
 9 |   (targets
10 |     astextra.ml
....
36 |     (copy ../static/boot/%{ocaml_version}/pa_ocaml_prelude.ml pa_ocaml_prelude.ml)
37 |     (copy ../static/boot/%{ocaml_version}/pa_parser.ml pa_parser.ml)
38 |     (copy ../static/boot/%{ocaml_version}/quote.ml quote.ml))))
Error: No rule found for static/boot/5.1.0/astextra.mli
File "boot/dune", line 8, characters 0-1196:
 8 | (rule
 9 |   (targets
10 |     astextra.ml
....
36 |     (copy ../static/boot/%{ocaml_version}/pa_ocaml_prelude.ml pa_ocaml_prelude.ml)
37 |     (copy ../static/boot/%{ocaml_version}/pa_parser.ml pa_parser.ml)
38 |     (copy ../static/boot/%{ocaml_version}/quote.ml quote.ml))))
Error: No rule found for static/boot/5.1.0/compare.ml
File "boot/dune", line 8, characters 0-1196:
 8 | (rule
 9 |   (targets
10 |     astextra.ml
....
36 |     (copy ../static/boot/%{ocaml_version}/pa_ocaml_prelude.ml pa_ocaml_prelude.ml)
37 |     (copy ../static/boot/%{ocaml_version}/pa_parser.ml pa_parser.ml)
38 |     (copy ../static/boot/%{ocaml_version}/quote.ml quote.ml))))
Error: No rule found for static/boot/5.1.0/helper.ml
File "boot/dune", line 8, characters 0-1196:
 8 | (rule
 9 |   (targets
10 |     astextra.ml
....
36 |     (copy ../static/boot/%{ocaml_version}/pa_ocaml_prelude.ml pa_ocaml_prelude.ml)
37 |     (copy ../static/boot/%{ocaml_version}/pa_parser.ml pa_parser.ml)
38 |     (copy ../static/boot/%{ocaml_version}/quote.ml quote.ml))))
Error: No rule found for static/boot/5.1.0/helper.mli
File "boot/dune", line 8, characters 0-1196:
 8 | (rule
 9 |   (targets
10 |     astextra.ml
....
36 |     (copy ../static/boot/%{ocaml_version}/pa_ocaml_prelude.ml pa_ocaml_prelude.ml)
37 |     (copy ../static/boot/%{ocaml_version}/pa_parser.ml pa_parser.ml)
38 |     (copy ../static/boot/%{ocaml_version}/quote.ml quote.ml))))
Error: No rule found for static/boot/5.1.0/iter.ml
File "boot/dune", line 8, characters 0-1196:
 8 | (rule
 9 |   (targets
10 |     astextra.ml
....
36 |     (copy ../static/boot/%{ocaml_version}/pa_ocaml_prelude.ml pa_ocaml_prelude.ml)
37 |     (copy ../static/boot/%{ocaml_version}/pa_parser.ml pa_parser.ml)
38 |     (copy ../static/boot/%{ocaml_version}/quote.ml quote.ml))))
Error: No rule found for static/boot/5.1.0/pa_ast.ml
File "boot/dune", line 8, characters 0-1196:
 8 | (rule
 9 |   (targets
10 |     astextra.ml
....
36 |     (copy ../static/boot/%{ocaml_version}/pa_ocaml_prelude.ml pa_ocaml_prelude.ml)
37 |     (copy ../static/boot/%{ocaml_version}/pa_parser.ml pa_parser.ml)
38 |     (copy ../static/boot/%{ocaml_version}/quote.ml quote.ml))))
Error: No rule found for static/boot/5.1.0/pa_default.ml
File "boot/dune", line 8, characters 0-1196:
 8 | (rule
 9 |   (targets
10 |     astextra.ml
....
36 |     (copy ../static/boot/%{ocaml_version}/pa_ocaml_prelude.ml pa_ocaml_prelude.ml)
37 |     (copy ../static/boot/%{ocaml_version}/pa_parser.ml pa_parser.ml)
38 |     (copy ../static/boot/%{ocaml_version}/quote.ml quote.ml))))
Error: No rule found for static/boot/5.1.0/pa_lexing.ml
File "boot/dune", line 8, characters 0-1196:
 8 | (rule
 9 |   (targets
10 |     astextra.ml
....
36 |     (copy ../static/boot/%{ocaml_version}/pa_ocaml_prelude.ml pa_ocaml_prelude.ml)
37 |     (copy ../static/boot/%{ocaml_version}/pa_parser.ml pa_parser.ml)
38 |     (copy ../static/boot/%{ocaml_version}/quote.ml quote.ml))))
Error: No rule found for static/boot/5.1.0/pa_main.ml
File "boot/dune", line 8, characters 0-1196:
 8 | (rule
 9 |   (targets
10 |     astextra.ml
....
36 |     (copy ../static/boot/%{ocaml_version}/pa_ocaml_prelude.ml pa_ocaml_prelude.ml)
37 |     (copy ../static/boot/%{ocaml_version}/pa_parser.ml pa_parser.ml)
38 |     (copy ../static/boot/%{ocaml_version}/quote.ml quote.ml))))
Error: No rule found for static/boot/5.1.0/pa_ocaml.ml
File "boot/dune", line 8, characters 0-1196:
 8 | (rule
 9 |   (targets
10 |     astextra.ml
....
36 |     (copy ../static/boot/%{ocaml_version}/pa_ocaml_prelude.ml pa_ocaml_prelude.ml)
37 |     (copy ../static/boot/%{ocaml_version}/pa_parser.ml pa_parser.ml)
38 |     (copy ../static/boot/%{ocaml_version}/quote.ml quote.ml))))
Error: No rule found for static/boot/5.1.0/pa_ocaml_prelude.ml
File "boot/dune", line 8, characters 0-1196:
 8 | (rule
 9 |   (targets
10 |     astextra.ml
....
36 |     (copy ../static/boot/%{ocaml_version}/pa_ocaml_prelude.ml pa_ocaml_prelude.ml)
37 |     (copy ../static/boot/%{ocaml_version}/pa_parser.ml pa_parser.ml)
38 |     (copy ../static/boot/%{ocaml_version}/quote.ml quote.ml))))
Error: No rule found for static/boot/5.1.0/pa_parser.ml
File "boot/dune", line 8, characters 0-1196:
 8 | (rule
 9 |   (targets
10 |     astextra.ml
....
36 |     (copy ../static/boot/%{ocaml_version}/pa_ocaml_prelude.ml pa_ocaml_prelude.ml)
37 |     (copy ../static/boot/%{ocaml_version}/pa_parser.ml pa_parser.ml)
38 |     (copy ../static/boot/%{ocaml_version}/quote.ml quote.ml))))
Error: No rule found for static/boot/5.1.0/quote.ml
```

Does that make any sense? Are there some other dependencies I'm missing not named in the readme and not hinted at in this error? Or is the OCaml/Dune version provided by Arch now too new for this library?

**Comment by rlepigre** [comment] 2023-12-27 23:14
The problem is that you're trying to install version 2.0.0, which is only compatible with older versions of OCaml. I would just install the latest version (3.0.0, here is the archive: https://github.com/rlepigre/ocaml-earley/archive/3.0.0.tar.gz).

**Comment by rlepigre** [comment] 2023-12-27 23:18
I created an actual release, since there was only a tag for 3.0.0. I'll close this, but feel free to re-open in case of further problem with this.

**Closed as completed by rlepigre** 2023-12-27 23:18 UTC

**Comment by alerque** [comment] 2023-12-28 08:48
Thanks! I did miss the newer tag since GitHub highlighted the release and I just typed that number into my build assuming it was the latest.

**Comment by alerque** [comment] 2023-12-28 09:20
Unfortunately my ultimate goal of building Patoline seems to be stymied because it depends on v2.x (due do use of `earley.ocaml` which was made private in v3.x). But thanks anyway.

**Comment by craff** [comment] 2023-12-28 10:43
Caleb Maclennan ***@***.***> writes:

> Unfortunately my ultimate goal of building Patoline seems to be stymied because it depends on v2.x (due do use of earley.ocaml which was made private in
> v3.x). But thanks anyway.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.

Hello,

Since, earley, I have build pacomb (https://github.com/craff/pacomb)
which is easier to maintain and which I update regularly.

I would like to use pacomb to resurect a parser for patoline with a ppx accepting
{pato|... |pato} for patoline syntax inside caml syntax, and
a parser for direct patoline syntax.

I have made experiments with my chaml syntax for simple_httpd
(https://github.com/craff/simple_httpd) that indicates that this will
work for patoline too.

The main problem is to find time to do that...

Cheers,
Christophe

--
Christophe Raffalli
tél: +689 87 23 11 48
web: http://raffalli.eu
my mails should pass DKIM/SPF tests/mes messages doivent passer les tests DKIM/SPF
